### ISSUE TITLE
State Control: Might need an overhaul

### ISSUE THREAD

**Issue by NichPang1** [CS2113-AY1819S1-F10-2/main#69]
#5 current implementation involves saving the whole MediBook in a list and iterate through. However, MediBook is just a container with reference to the Person objects and our ab3 is not immutable unlike ab4 so changes like deleting/adding/clearing the list can be undone but changes made to the Person objects itself cant be undone.

**Comment by OngJiaJian** [comment]
Could you please elaborate?

**Comment by C-E-OOI** [comment]
does that mean if i edit the person attributes such as the appointments or the address, it would not be recorded?

**Comment by NichPang1** [comment]
it will be recorded but it cant be undone. Anyway, a new undo/redo has been implemented which doesnt have this issue. However, every new command that we add in the future that is undoable will need to extend from the undoable class and know how to undo/redo what they have done

**Comment by NichPang1** [comment]
Currently only 4 commands are implemented as i have yet to read up your parts to implement the undo/redo for your other commands. Will be done next week or something

**Comment by NichPang1** [comment]
Now supports Unlink and Change pw

**Comment by NichPang1** [comment]
No plans to implement it to support edit schedule due to the lack of time
